解决requirements.txt不存在问题
(venv3.11) PS C:\Users\alice\Desktop\xanalyzer> python -m build
* Creating venv isolated environment...
* Installing packages in isolated environment... (setuptools >= 40.8.0, wheel)
* Getting build dependencies for sdist...
running egg_info
writing xanalyzer.egg-info\PKG-INFO
writing dependency_links to xanalyzer.egg-info\dependency_links.txt
writing entry points to xanalyzer.egg-info\entry_points.txt
writing requirements to xanalyzer.egg-info\requires.txt
writing top-level names to xanalyzer.egg-info\top_level.txt
reading manifest file 'xanalyzer.egg-info\SOURCES.txt'
writing manifest file 'xanalyzer.egg-info\SOURCES.txt'
* Building sdist...
running sdist
running egg_info
writing xanalyzer.egg-info\PKG-INFO
writing dependency_links to xanalyzer.egg-info\dependency_links.txt
writing entry points to xanalyzer.egg-info\entry_points.txt
writing requirements to xanalyzer.egg-info\requires.txt
writing top-level names to xanalyzer.egg-info\top_level.txt
reading manifest file 'xanalyzer.egg-info\SOURCES.txt'
writing manifest file 'xanalyzer.egg-info\SOURCES.txt'
running check
creating xanalyzer-1.1.0
creating xanalyzer-1.1.0\tests
creating xanalyzer-1.1.0\xanalyzer
creating xanalyzer-1.1.0\xanalyzer.egg-info
creating xanalyzer-1.1.0\xanalyzer\data
creating xanalyzer-1.1.0\xanalyzer\data\yara_rules
creating xanalyzer-1.1.0\xanalyzer\data\yara_rules\packers
creating xanalyzer-1.1.0\xanalyzer\file_process
copying files to xanalyzer-1.1.0...
copying README.md -> xanalyzer-1.1.0
copying setup.py -> xanalyzer-1.1.0
copying tests\__init__.py -> xanalyzer-1.1.0\tests
copying tests\test_elf_size.py -> xanalyzer-1.1.0\tests
copying tests\test_exe_import_api.py -> xanalyzer-1.1.0\tests
copying tests\test_filetype.py -> xanalyzer-1.1.0\tests
copying tests\test_packer.py -> xanalyzer-1.1.0\tests
copying tests\test_pe_cert_name.py -> xanalyzer-1.1.0\tests
copying tests\test_pe_compile_time.py -> xanalyzer-1.1.0\tests
copying tests\test_pe_dll_name.py -> xanalyzer-1.1.0\tests
copying tests\test_pe_pdb.py -> xanalyzer-1.1.0\tests
copying tests\test_pe_resource.py -> xanalyzer-1.1.0\tests
copying tests\test_pe_size.py -> xanalyzer-1.1.0\tests
copying tests\test_pe_versioninfo.py -> xanalyzer-1.1.0\tests
copying tests\test_recommended_tool.py -> xanalyzer-1.1.0\tests
copying tests\test_str.py -> xanalyzer-1.1.0\tests
copying tests\test_windows_style_file_size.py -> xanalyzer-1.1.0\tests
copying tests\test_yara_chinese_path.py -> xanalyzer-1.1.0\tests
copying xanalyzer\VERSION -> xanalyzer-1.1.0\xanalyzer
copying xanalyzer\__init__.py -> xanalyzer-1.1.0\xanalyzer
copying xanalyzer\config.py -> xanalyzer-1.1.0\xanalyzer
copying xanalyzer\file.py -> xanalyzer-1.1.0\xanalyzer
copying xanalyzer\main.py -> xanalyzer-1.1.0\xanalyzer
copying xanalyzer\url.py -> xanalyzer-1.1.0\xanalyzer
copying xanalyzer\utils.py -> xanalyzer-1.1.0\xanalyzer
copying xanalyzer.egg-info\PKG-INFO -> xanalyzer-1.1.0\xanalyzer.egg-info
copying xanalyzer.egg-info\SOURCES.txt -> xanalyzer-1.1.0\xanalyzer.egg-info
copying xanalyzer.egg-info\dependency_links.txt -> xanalyzer-1.1.0\xanalyzer.egg-info
copying xanalyzer.egg-info\entry_points.txt -> xanalyzer-1.1.0\xanalyzer.egg-info
copying xanalyzer.egg-info\requires.txt -> xanalyzer-1.1.0\xanalyzer.egg-info
copying xanalyzer.egg-info\top_level.txt -> xanalyzer-1.1.0\xanalyzer.egg-info
copying xanalyzer\data\UserDB.TXT -> xanalyzer-1.1.0\xanalyzer\data
copying xanalyzer\data\tools_info.json -> xanalyzer-1.1.0\xanalyzer\data
copying xanalyzer\data\yara_rules\packers\UPX_PE.yar -> xanalyzer-1.1.0\xanalyzer\data\yara_rules\packers
copying xanalyzer\file_process\__init__.py -> xanalyzer-1.1.0\xanalyzer\file_process
copying xanalyzer\file_process\elf.py -> xanalyzer-1.1.0\xanalyzer\file_process
copying xanalyzer\file_process\pe.py -> xanalyzer-1.1.0\xanalyzer\file_process
copying xanalyzer.egg-info\SOURCES.txt -> xanalyzer-1.1.0\xanalyzer.egg-info
Writing xanalyzer-1.1.0\setup.cfg
Creating tar archive
removing 'xanalyzer-1.1.0' (and everything under it)
* Building wheel from sdist
* Creating venv isolated environment...
* Installing packages in isolated environment... (setuptools >= 40.8.0, wheel)
* Getting build dependencies for wheel...
Traceback (most recent call last):
  File "C:\Users\alice\Desktop\xanalyzer\venv3.11\Lib\site-packages\pyproject_hooks\_in_process\_in_process.py", line 373, in <module>
    main()
  File "C:\Users\alice\Desktop\xanalyzer\venv3.11\Lib\site-packages\pyproject_hooks\_in_process\_in_process.py", line 357, in main
    json_out["return_val"] = hook(**hook_input["kwargs"])
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\alice\Desktop\xanalyzer\venv3.11\Lib\site-packages\pyproject_hooks\_in_process\_in_process.py", line 134, in get_requires_for_build_wheel
    return hook(config_settings)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\alice\AppData\Local\Temp\build-env-z299lc4z\Lib\site-packages\setuptools\build_meta.py", line 327, in get_requires_for_build_wheel
    return self._get_build_requires(config_settings, requirements=[])
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\alice\AppData\Local\Temp\build-env-z299lc4z\Lib\site-packages\setuptools\build_meta.py", line 297, in _get_build_requires
    self.run_setup()
  File "C:\Users\alice\AppData\Local\Temp\build-env-z299lc4z\Lib\site-packages\setuptools\build_meta.py", line 497, in run_setup
    super().run_setup(setup_script=setup_script)
  File "C:\Users\alice\AppData\Local\Temp\build-env-z299lc4z\Lib\site-packages\setuptools\build_meta.py", line 313, in run_setup
    exec(code, locals())
  File "<string>", line 26, in <module>
FileNotFoundError: [Errno 2] No such file or directory: 'requirements.txt'

ERROR Backend subprocess exited when trying to invoke get_requires_for_build_wheel

使用该链接使用方法可解决：
https://medium.com/@alisidaniel/filenotfounderror-errno-2-no-such-file-or-directory-requirements-txt-python-3-12-3ff370969d44